name: curv
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip>=20.*
  - ase>=3.*
  - jupyter>=1.*
  - matplotlib>=3.*
  - nglview>=2.*
  - numpy>=1.20.*
  - pandas>=2.*
  - pyyaml>=6.0
  - pymatgen>=2022.0.17
  - pip:
    - dash>=2.1.0 
    - dash-bio>=1.0.1
    - git+git://github.com/gVallverdu/pychemcurv.git
